name: FM CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt update && sudo apt install -y g++

      - name: Build FM core
        run: |
          g++ -std=c++17 -pthread -I. \
          -o core \
          main.cpp \
          CORE/src/utils.cpp \
          CORE/src/cp.cpp \
          CORE/src/rn.cpp \
          CORE/src/rm.cpp \
          CORE/src/mv.cpp \
          CORE/src/cd.cpp \
          CORE/src/mk.cpp \
          CORE/src/cat.cpp \
          CORE/src/find.cpp \
          CORE/src/edit.cpp \
          CORE/src/info.cpp \
          CORE/src/ls.cpp \
          CORE/src/pwd.cpp \
          CORE/src/oscmd.cpp \
          CORE/src/help.cpp

      - name: Verify executable
        run: |
          test -f core
          echo "Build successful"
      - name: Verify executable
        run: |
          test -f fm
          echo "Build successful"
